/* Vendors the lucide icons the design uses into a single module, so the game
   ships them offline instead of pulling the Iconify CDN (which the PWA and the
   CSP both rule out). Re-run after adding an icon name below.
     node scripts/gen-lucide.mjs                                            */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const dir = join(root, 'node_modules', 'lucide-static', 'icons')

// every lucide name the Stowage Bridge design references
const NAMES = `alert-triangle arrow-down-to-line arrow-right atom ban battery-charging bed-double check
check-circle chevron-right circle-check circle-off coins crosshair dot droplet flame flame-kindling fuel
graduation-cap hand-coins inbox layout-grid lock maximize menu minus move move-up-right orbit package
package-plus pen-line play plus rocket route shield shield-check shopping-bag skip-forward snowflake
square-dashed store tag thermometer-snowflake trash-2 triangle-alert trophy user-plus user-round
user-round-minus users waypoints weight wind x zap share-2 flag`.split(/\s+/).filter(Boolean)

const out = {}
const missing = []
for (const n of NAMES) {
  let svg
  try {
    svg = readFileSync(join(dir, n + '.svg'), 'utf8')
  } catch {
    missing.push(n)
    continue
  }
  // keep only the drawing, not lucide's wrapper: our <svg> supplies the frame
  const inner = svg
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/<svg[\s\S]*?>/, '')
    .replace(/<\/svg>/, '')
    .replace(/\s+/g, ' ')
    .trim()
  if (inner) out[n] = inner
}

if (missing.length) console.warn('not in this lucide build:', missing.join(', '))

const body = Object.entries(out)
  .map(([k, v]) => `  '${k}': '${v.replace(/'/g, "\\'")}'`)
  .join(',\n')

writeFileSync(
  join(root, 'web', 'src', 'ui', 'lucide.ts'),
  `/* GENERATED by scripts/gen-lucide.mjs from lucide-static (ISC). Do not edit.\n` +
    `   ${Object.keys(out).length} icons, vendored so the PWA works offline. */\n` +
    `export const LUCIDE: Record<string, string> = {\n${body}\n}\n`
)
console.log(`wrote ${Object.keys(out).length} icons to web/src/ui/lucide.ts`)
